"""UUID

Revision ID: 36be19a01bfe
Revises: 8f53167fbe11
Create Date: 2023-11-03 16:14:09.013113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
# revision identifiers, used by Alembic.
revision: str = '36be19a01bfe'
down_revision: Union[str, None] = '8f53167fbe11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";")
    op.execute("ALTER TABLE url_table ADD COLUMN new_id UUID;")
    op.execute("UPDATE url_table SET new_id = uuid_generate_v4();")
    op.execute("ALTER TABLE url_table DROP COLUMN id;")
    op.execute("ALTER TABLE url_table RENAME COLUMN new_id TO id;")

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE url_table ADD COLUMN old_id INTEGER;")
    op.execute("UPDATE url_table SET old_id = NULL;")  # or set to a default value
    op.execute("ALTER TABLE url_table DROP COLUMN id;")
    op.execute("ALTER TABLE url_table RENAME COLUMN old_id TO id;")
    # ### end Alembic commands ###