version: "3"
services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn backend.backend_api.api:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - .:/app
    ports:
      - 8000:5000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SQLDB_USER=${WEB_SCRAPER_SQLDB_USERNAME}
      - SQLDB_PASS=${WEB_SCRAPER_SQLDB_PASSWORD}
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.12.7-management-alpine
    ports:
      - 5672:5672 # RabbitMQ
      - 15672:15672 # management plugin

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A backend.backend_api.services.WebScraper worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SQLDB_USER=${WEB_SCRAPER_SQLDB_USERNAME}
      - SQLDB_PASS=${WEB_SCRAPER_SQLDB_PASSWORD}
    depends_on:
      - rabbitmq

  db:
    image: postgres
    volumes:
      - web_scraper_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=web_scraper_db
    ports:
      - "5433:5432"

volumes:
  web_scraper_db_data:
